-- =============================================================
-- 0002_core_tables.sql
-- Базовые таблицы доменной модели и отчетов.
-- Порядок: organizations -> organization_members -> report_metadata -> *reports -> *monthly_summaries
-- =============================================================

-- Организации
create table if not exists public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  external_id text unique
);

-- Связь пользователей и организаций
create table if not exists public.organization_members (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  organization_id uuid not null references public.organizations (id) on delete cascade,
  role text not null check (role in ('admin', 'member')),
  created_at timestamptz default now(),
  unique (user_id, organization_id)
);

-- Метаданные отчетов (тип/дата)
create table if not exists public.report_metadata (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  report_type text not null,   -- допустимые значения задаются на уровне приложений
  report_date date not null,
  created_at timestamp default now(),
  updated_at timestamp,
  unique (organization_id, report_type, report_date)
);

-- Таблица строк отчета: Денежные средства (банк/касса)
create table if not exists public.cash_bank_report_items (
  id uuid primary key default gen_random_uuid(),
  report_id uuid not null references public.report_metadata (id) on delete cascade,
  subconto text,
  account_name text not null,
  balance_start decimal(15, 2),
  income_amount decimal(15, 2),
  expense_amount decimal(15, 2),
  balance_current decimal(15, 2),
  account_type text check (account_type in ('bank', 'cash', 'total')),
  level integer,
  currency text not null,
  is_total_row boolean default false,
  created_at timestamptz default now() not null,
  -- Иерархия
  parent_id uuid references public.cash_bank_report_items (id) on delete set null,
  account_id text,
  parent_account_id text
);

-- Таблица строк отчета: Товарные запасы / оборачиваемость
create table if not exists public.inventory_turnover_report_items (
  id uuid primary key default gen_random_uuid(),
  report_id uuid not null references public.report_metadata (id) on delete cascade,
  category_name text not null,
  parent_category_id uuid references public.inventory_turnover_report_items (id) on delete set null,
  quantity_pairs integer,
  balance_rub decimal(15, 2),
  dynamics_start_month_rub decimal(15, 2),
  dynamics_start_month_percent decimal(5, 2),
  dynamics_start_year_rub decimal(15, 2),
  dynamics_start_year_percent decimal(5, 2),
  turnover_days integer,
  level integer,
  is_total_row boolean default false
);

-- Таблица строк отчета: Дебиторка/кредит
create table if not exists public.debt_reports_items (
  id uuid primary key default gen_random_uuid (),
  report_id uuid not null references public.report_metadata (id) on delete cascade,
  debt_amount numeric not null,
  overdue_amount numeric not null,
  credit_amount numeric not null,
  is_total_row boolean default false not null,
  client_name text not null,
  parent_client_id uuid references public.debt_reports_items (id) on delete set null,
  created_at timestamptz default now(),
  level int
);

-- Таблица строк отчета: План-факт
create table if not exists public.plan_fact_reports_items (
  id uuid primary key default gen_random_uuid (),
  report_id uuid not null references public.report_metadata (id) on delete cascade,
  plan_amount numeric not null,
  fact_amount numeric not null,
  execution_percent numeric not null,
  is_total_row boolean default false not null,
  created_at timestamptz default now() not null,
  -- Иерархия и метаданные
  category_name text,
  parent_id uuid references public.plan_fact_reports_items (id) on delete set null,
  period_type text,     -- 'day' | 'month' | 'year' (по договоренности приложений)
  level integer,
  is_expandable boolean
);

-- Ежемесячные агрегаты (populate — доверенный бэкенд)
create table if not exists public.cash_bank_monthly_summaries (
  organization_id uuid not null references public.organizations (id) on delete cascade,
  year integer not null check (year between 1900 and 2100),
  month integer not null check (month between 1 and 12),
  account_type text not null,
  avg_balance decimal(15, 2),
  total_income decimal(15, 2),
  total_expense decimal(15, 2),
  primary key (organization_id, year, month, account_type)
);

create table if not exists public.inventory_monthly_summaries (
  organization_id uuid not null references public.organizations (id) on delete cascade,
  year integer not null,
  month integer not null,
  category_path text,
  avg_balance_rub decimal(15, 2),
  avg_turnover_days integer,
  primary key (organization_id, year, month, category_path)
);

create table if not exists public.debt_monthly_summaries (
  organization_id uuid references public.organizations (id) on delete cascade,
  year int not null,
  month int not null,
  client_name text not null,
  total_debt numeric not null,
  total_overdue numeric not null,
  total_credit numeric not null,
  primary key (organization_id, year, month, client_name)
);

create table if not exists public.plan_fact_monthly_summaries (
  organization_id uuid references public.organizations (id) on delete cascade,
  year int not null,
  month int not null,
  category_name text not null,
  total_plan numeric not null,
  total_fact numeric not null,
  execution_percent numeric not null,
  primary key (organization_id, year, month, category_name)
);
